# Generated by Django 6.0.7 on 2026-07-13 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0004_remove_product_sku_alter_category_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outbound_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('destination', models.CharField(max_length=100)),
                ('outbound_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Outbound',
                'verbose_name_plural': 'Outbounds',
                'db_table': 'outbounds',
                'ordering': ['-outbound_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OutboundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('batch_information', models.JSONField(blank=True, default=list)),
                ('outbound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='outbound.outbound')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_items', to='master.product')),
            ],
            options={
                'verbose_name': 'Outbound Item',
                'verbose_name_plural': 'Outbound Items',
                'db_table': 'outbound_items',
                'ordering': ['id'],
            },
        ),
    ]
