# Generated by Django 6.0.7 on 2026-07-12 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_alter_bin_options_alter_bin_id_alter_bin_table'),
        ('master', '0004_remove_product_sku_alter_category_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('received_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbounds', to='master.supplier')),
            ],
            options={
                'verbose_name': 'Inbound',
                'verbose_name_plural': 'Inbounds',
                'db_table': 'inbounds',
                'ordering': ['-received_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InboundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('expired_date', models.DateField()),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_items', to='inventory.bin')),
                ('inbound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inbound.inbound')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_items', to='master.product')),
            ],
            options={
                'verbose_name': 'Inbound Item',
                'verbose_name_plural': 'Inbound Items',
                'db_table': 'inbound_items',
                'ordering': ['id'],
            },
        ),
    ]
