# Generated by Django 6.0.7 on 2026-07-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bin',
            options={'ordering': ['code'], 'verbose_name': 'Bin', 'verbose_name_plural': 'Bins'},
        ),
        migrations.AlterField(
            model_name='bin',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='bin',
            table='bins',
        ),
    ]
