# Generated by Django 6.0.7 on 2026-07-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
